# Generated by Django 3.0.5 on 2021-08-07 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.ForeignKey(default='1', editable=False, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
