# Generated by Django 3.0.5 on 2021-06-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='preferred_currency',
        ),
    ]
