# Generated by Django 3.0.5 on 2022-03-10 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0002_auto_20220309_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingdeposit',
            old_name='is_approved',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='pendingdeposit',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='expected_maximum_balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='past_deposit_earning',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='past_deposits',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='plan_end',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='plan_start',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='previous_plan',
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.FloatField(default=0.0)),
                ('plan_start', models.DateTimeField(auto_now_add=True)),
                ('plan_end', models.DateTimeField()),
                ('expected_earning', models.FloatField(blank=True, default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_investment', to='wallet.Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
