# Generated by Django 3.0.5 on 2022-03-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20220310_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingdeposit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
