# Generated by Django 3.0.5 on 2021-07-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20210703_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='54545', editable=False, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coin',
            field=models.CharField(max_length=10),
        ),
    ]
