# Generated by Django 3.0.5 on 2022-03-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20220310_0526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='initial_amount',
            new_name='amount',
        ),
    ]
