# Generated by Django 3.0.5 on 2022-03-12 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0006_auto_20220310_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-plan_start']},
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='plan_is_active',
        ),
        migrations.AlterField(
            model_name='pendingdeposit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pending_deposit', to=settings.AUTH_USER_MODEL),
        ),
    ]
