# Generated by Django 3.0.5 on 2021-07-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20210721_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='deposit_earning',
        ),
    ]
