# Generated by Django 3.0.5 on 2022-03-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_auto_20220315_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
