# Generated by Django 3.0.5 on 2021-07-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_remove_wallet_deposit_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='past_deposit_earning',
            field=models.FloatField(default=0.0),
        ),
    ]
