# Generated by Django 3.0.5 on 2021-08-07 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_wallet_past_deposit_earning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='bonus_amount',
        ),
        migrations.AddField(
            model_name='wallet',
            name='previous_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_plan', to='wallet.Plan'),
        ),
    ]
