# Generated by Django 3.0.5 on 2022-03-20 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_investment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
