# Generated by Django 3.0.5 on 2022-03-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_investment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='pendingdeposit',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='investment',
            name='plan_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='plan_start',
            field=models.DateTimeField(null=True),
        ),
    ]
