# Generated by Django 3.0.5 on 2022-03-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_auto_20210807_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='admin',
        ),
    ]
