# Generated by Django 3.0.5 on 2022-03-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_auto_20220320_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='allow_automatic_investment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
