# Generated by Django 3.0.5 on 2022-03-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_auto_20220324_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='maximum investment for thie plan,currency is USD', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='min_cost',
            field=models.DecimalField(decimal_places=2, help_text='minimum investment for thie plan,currency is USD', max_digits=20),
        ),
    ]
