# Generated by Django 3.0.5 on 2022-03-07 04:51

from django.db import migrations, models
import wallet.models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_auto_20220306_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingdeposit',
            name='coin',
        ),
        migrations.AddField(
            model_name='pendingdeposit',
            name='payment_method',
            field=models.CharField(choices=[('USDT', 'USDT'), ('ETH', 'ETH'), ('BTC', 'BTC'), ('LTC', 'LTC')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingdeposit',
            name='payment_proof',
            field=models.FileField(default='', upload_to=wallet.models.PendingDeposit.get_path),
            preserve_default=False,
        ),
    ]
