# Generated by Django 3.0.5 on 2022-05-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_auto_20220331_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingdeposit',
            name='payment_method',
            field=models.CharField(choices=[('USDT(BEP20)', 'USDT(BEP20)'), ('USDT(TRC20)', 'USDT(TRC20)'), ('ETH', 'ETH'), ('BTC', 'BTC'), ('LTC', 'LTC')], max_length=20),
        ),
    ]
