# Generated by Django 3.0.5 on 2021-06-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20210624_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='myadmin',
            name='total_revenue',
            field=models.FloatField(default=0.0),
        ),
    ]
