# Generated by Django 3.0.5 on 2021-07-03 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_auto_20210625_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myadmin',
            name='enable_verification_registration',
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_email_verify', models.BooleanField(default=False, help_text='enable email verification on registration')),
                ('enable_newsletters', models.BooleanField(default=False)),
                ('enable_transaction_emails', models.BooleanField(default=False)),
                ('enable_referral_bonus', models.BooleanField(default=False)),
                ('enable_watsapp_chat', models.BooleanField(default=False)),
                ('enable_social_links', models.BooleanField(default=False)),
                ('enable_registration_emails', models.BooleanField(default=False, help_text='send emails to users upon registration')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='myadmin.MyAdmin')),
            ],
        ),
    ]
