# Generated by Django 3.0.5 on 2021-07-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_auto_20210703_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='myadmin.MyAdmin'),
        ),
    ]
