# Generated by Django 3.0.5 on 2021-07-18 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_auto_20210704_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='myadmin',
            name='free_plan_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myadmin',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myadmin',
            name='subscription_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
