# Generated by Django 3.0.5 on 2021-07-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='myadmin',
            name='secret_pin',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
