# Generated by Django 3.0.5 on 2021-08-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_myadmin_secret_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myadmin',
            name='secret_id',
        ),
    ]
