# Generated by Django 3.0.5 on 2021-08-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_remove_myadmin_secret_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='transaction_reference',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
